language: java
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
deploy:
  provider: releases
  api_key: "$GITHUB_AUTH_TOKEN"
  file: build/libs/rundeck-ec2-nodes-plugin-*.jar
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
env:
  global:
    secure: Z5sNv+8SwzWTPnNDSGiQt063BKwhkurUMjuTOnu1ZLlkoVZfu7cn1fiWV9JRdb7/Asj/jA+EoVq+j8iSM2WQjrD6Nn51D7/TSiKju1ISVH4BOzAHOJGrGYOySgU2Jhc2jvO/oni3DJN261jKg5vwmQpZexteCKE3UflMmhNMbGU=
